# Created using ManifestCreatorWebsite

Id: Obsidian.Obsidian
Version: 0.10.13
Name: Obsidian
Publisher: Obsidian
License: Copyright © 2021 Dynalist Inc.
Description: Obsidian
Switches: {}
Installers:
- Arch: x86
  Url: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.10.13/Obsidian.0.10.13.exe
  Sha256: 99157617AD539A5D88EB0885D56C119CE90F920A997ABC3B5CD38C5D5B459A25
  InstallerType: nullsoft
  Switches: {}
ManifestVersion: 0.1.0
