# Created using 
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Multifile.Yaml.MsixTest
PackageVersion: 0.1.2.3
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

