# Created using wingetcreate

Id: Ditto.Ditto
Version: 3.23.124.0
Name: Ditto
Publisher: Ditto
AppMoniker: Ditto
License: GNU General Public License version 3.0 (GPLv3)
Tags: Ditto Clipboard
InstallerType: exe
Description: Ditto is an extension to the standard windows clipboard. It saves each item placed on the clipboard allowing you access to any of those items at a later time.
Homepage: https://ditto-cp.sourceforge.io/
LicenseUrl: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)
Installers:
- Arch: x86
  Url: https://netactuate.dl.sourceforge.net/project/ditto-cp/Ditto/3.23.124.0/DittoSetup_3_23_124_0.exe
  Sha256: 743FBB29F52E740EBFE220485FE2A2C1244994F979F4337B8B5452BE3B87EF63
  Switches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS
ManifestVersion: 0.1.0
