# Created using WingetCreateUnitTests
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json

PackageIdentifier: TestPublisher.TestApp
PackageVersion: 0.1.2
PackageLocale: en-US
Publisher: Test publisher
PackageName: Test app
License: MIT
ShortDescription: A manifest used for testing.
Installers:
- Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v-0.2.10771-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
  InstallerSha256: 8A052767127A6E2058BAAE03B551A807777BB1B726650E2C7E92C3E92C8DF80D
ManifestType: singleton
ManifestVersion: 1.0.0
