# Created using 
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: WingetCreateE2E.Yaml.ZipTest
PackageVersion: 1.2.3.4
PackageLocale: en-US
Publisher: WingetCreateE2E
Author: Microsoft
PackageName: ZipTest
License: MIT
LicenseUrl: https://github.com/microsoft/winget-create
ShortDescription: Testing WingetCreate with a zip
Tags:
- Windows Package Manager
- winget create
- package manager
- utility
- tool
- test
ManifestType: defaultLocale
ManifestVersion: 1.9.0
