# Created using wingetcreate

Id: Node.jsFoundation.Node.js
Version: 10.15.3
Name: Node.js
Publisher: Node.js Foundation
License: test
Description: test
Installers:
- Arch: x64
  Url: https://nodejs.org/dist/v10.15.3/node-v10.15.3-x64.msi
  Sha256: 46B3D03C96DE0B9E7D3A204C67772759283221F5E58AC225DF813076A65E2738
  Language: en-US
  InstallerType: msi
ManifestVersion: 0.1.0
